### ISSUE TITLE
Don't use inline CSS

### ISSUE THREAD

**Issue by avetisk** [Samuel-Marien/afpa_project#1]
https://github.com/Samuel-Marien/afpa_project/blob/014ad44f8ff20b1ebcbc55add1a0263141bde6d7/components/BackButton.js#L4

Either use an [utility class from Bootstrap](https://getbootstrap.com/docs/5.0/utilities/api/) or customise with `@emotion/styled`.

**Comment by Samuel-Marien** [comment]
fixed

**Comment by Samuel-Marien** [comment]
fix : Don't use inline CSS #1
